#!/usr/bin/env python3

import sys
from rqt_gui.main import Main
from canopen_rqt.canopen_controller import CANopenController

plugin = 'canopen_rqt.canopen_controller.CANopenController'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))